name: Update Helm Chart

on:
  push:
    branches:
      - main

jobs:

  sync:
    runs-on: ubuntu-24.04
    env:
      # github-releases: immich-app/immich-charts
      IMMICH_VERSION: 'immich-0.10.3'

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - name: Copy helm-chart folder
        run: |
          rm -rf charts
          mkdir -p charts
          helm pull oci://ghcr.io/immich-app/immich-charts/immich --untar --version ${IMMICH_VERSION#immich-}
          mv immich charts/

      - name: Commit and push changes
        run: |
          set -ex;
          echo "Configuring git user"
          git config user.name "Forgjo Actions"
          git config user.email "forgejo-actions@${FORGEJO_SERVER_URL#*://}"
          git add charts
          git commit -m "Update helm-chart to tag ${IMMICH_VERSION#immich-}" || echo "No changes to commit"
          git push
          git fetch --prune --prune-tags --all
          git tag --list
          git tag -a ${IMMICH_VERSION#immich-} -m "Version ${IMMICH_VERSION#immich-} release" || echo "tag allready present"
          git push origin ${IMMICH_VERSION#immich-} || echo "No need to push"
