annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - "deps: update dependency helm to v4.3.0 (#403)"
    - "deps: update dependency yq to v4.54.1 (#408)"
    - "deps: update docker.io/valkey/valkey docker tag to v9.2 (#406)"
    - "deps: update helm release common to v5.2.1 (#407)"
    - "deps: update testing dependencies (#404)"
apiVersion: v2
appVersion: v3.2.0
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 5.2.1
description: A chart to power Immich (immich.app) running on kubernetes
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
maintainers:
- email: boet@futo.org
  name: bo0tzz
name: immich
sources:
- https://github.com/immich-app/immich-charts/tree/main/charts/immich
- https://github.com/immich-app/immich
version: 0.13.3
