annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: removed
      description: Breaking changes
      links:
        - name: Release notes
          url: https://github.com/immich-app/immich-charts/releases/tag/immich-0.10.0
    - kind: removed
      description: Postgres subchart
    - kind: removed
      description: Redis subchart
    - kind: changed
      description: Common library dependency update
apiVersion: v2
appVersion: v2.0.0
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.3.0
description: A chart to power Immich (immich.app) running on kubernetes
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
maintainers:
- email: 5434875+PixelJonas@users.noreply.github.com
  name: PixelJonas
- email: immich@bo0tzz.me
  name: bo0tzz
name: immich
sources:
- https://github.com/immich-app/immich-charts/tree/main/charts/immich
- https://github.com/immich-app/immich
version: 0.10.0
