annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: added
      description: Proper generated changelogs on GitHub
    - kind: fixed
      description: Set the deployment strategy to RollingUpdate, which should have been the default all along.
apiVersion: v2
appVersion: v1.119.0
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.4.0
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 16.0.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.11.3
description: A chart to power Immich (immich.app) running on kubernetes
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
maintainers:
- email: 5434875+PixelJonas@users.noreply.github.com
  name: PixelJonas
- email: immich@bo0tzz.me
  name: bo0tzz
name: immich
sources:
- https://github.com/immich-app/immich-charts/tree/main/charts/immich
- https://github.com/immich-app/immich
version: 0.9.1
